### ISSUE TITLE
Keywords In Double Quotes

### ISSUE THREAD

**Issue by jinghaihan** [erosman/CodeMirror-plus#3]
When the keyword appears in single quotation marks, it is normally added with "cm string", but when it appears in double quotation marks, its class name is "cm keyword"

Is there any good solution?

**Comment by erosman** [comment]
Can you post an example?

**Comment by jinghaihan** [comment]
> 
Hello, you can enter "CREATE" as the test. "yarn" installs dependencies and then "yarn dev" opens the project
https://github.com/jinghaihan/codemirror-sample

**Comment by jinghaihan** [comment]
![codemirror-plus](https://user-images.githubusercontent.com/39728926/184588511-87d5285a-ae69-46ab-a6fe-16b463dbc311.jpg)

**Comment by erosman** [comment]
As in your image, that is how CodeMirror processes them.

I meant, keywords in the config e.g.

```js
const editor = CodeMirror(document.body, {
  lineNumbers: true,
  mode:  "javascript",
  keyword: {
    "word1": "style1",
    "word2": "style1",
    "word3": "style1",
    "example\.com": "style2",
    "abc\\d+": "style2"
  }
});
```

**Comment by jinghaihan** [comment]
But I found that as a keyword, "select" is only processed as cm string
![codemirror-plus](https://user-images.githubusercontent.com/39728926/184589045-4258b73b-cfb7-401e-987f-89b1f8887846.jpg)

**Comment by jinghaihan** [comment]
Does addoverlay have higher priority than judging whether it is between quotation marks?

**Comment by erosman** [comment]
That might be the case in CodeMirror. You can ask [codemirror5](https://github.com/codemirror/codemirror5).

**Comment by jinghaihan** [comment]
Thanks for your reply
